name: Build wolfram-app-discovery executable

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The commit SHA or tag to build"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:

    build-release-artifacts:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                build: [linux-gnu, linux-musl, macos-x86-64, macos-arm, win-msvc]
                include:
                -   build: linux-gnu
                    os: ubuntu-20.04
                    target: x86_64-unknown-linux-gnu

                -   build: linux-musl
                    os: ubuntu-20.04
                    target: x86_64-unknown-linux-musl

                -   build: macos-x86-64
                    os: macos-12
                    target: x86_64-apple-darwin

                -   build: macos-arm
                    os: macos-12
                    target: aarch64-apple-darwin

                -   build: win-msvc
                    os: windows-2019
                    target: x86_64-pc-windows-msvc

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.event.inputs.ref }}

            -   name: Install Rust target
                run: rustup target add ${{ matrix.target }}

            -   name: Build ${{ matrix.build }}
                run: cargo build --release --features=cli --target ${{ matrix.target }} --verbose

            # On macOS and Linux cargo will generate an executable with the name
            # `wolfram-app-discovery`. On Windows, it has the name `wolfram-app-discovery.exe`.
            #
            # Save that conditional result to an environment variable for later reference.
            -   name: Determine executable name
                shell: bash
                run: |
                    if [ "${{ matrix.os }}" = "windows-2019"]; then
                        echo "EXE_NAME=wolfram-app-discovery.exe" >> $GITHUB_ENV
                    else
                        echo "EXE_NAME=wolfram-app-discovery" >> $GITHUB_ENV
                    fi

            -   name: Construct platform release archive
                run: |
                    staging="wolfram-app-discovery--${{ github.event.inputs.ref }}--${{ matrix.target}}"

                    echo "ARTIFACT=$staging" >> $GITHUB_ENV

                    cp {README.md,docs/CommandLineHelp.md}  "$staging/"

                    cp "target/${{ matrix.target }}/release/${{ env.EXE_NAME }}"  "$staging/"

            -   name: Upload artifact
                uses: actions/upload-artifact@v3
                with:
                    name: wolfram-app-discovery--${{ github.event.inputs.ref }}--${{ matrix.target}}
                    path: ${{ env.ARTIFACT }}

