name: Build wolfram-app-discovery executable

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The commit SHA or tag to build"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
        
    - name: Install MUSL target
      run: rustup target add x86_64-unknown-linux-musl
        
    - name: Build — Linux GNU
      run: cargo build --release --features=cli --target x86_64-unknown-linux-gnu --verbose

    - name: Build — Linux MUSL
      run: cargo build --release --features=cli --target x86_64-unknown-linux-musl --verbose
      
    - name: Upload GNU executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: wolfram-app-discovery--${{ github.event.inputs.ref }}--x86_64-unknown-linux-gnu 
        path: target/x86_64-unknown-linux-gnu/release/wolfram-app-discovery
      
    - name: Upload MUSL executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: wolfram-app-discovery--${{ github.event.inputs.ref }}--x86_64-unknown-linux-musl 
        path: target/x86_64-unknown-linux-musl/release/wolfram-app-discovery
        
  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Build — MSVC
      run: cargo build --release --features=cli --target x86_64-pc-windows-msvc --verbose
      
    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: wolfram-app-discovery--${{ github.event.inputs.ref }}--x86_64-pc-windows-msvc.exe
        path: target/x86_64-pc-windows-msvc/release/wolfram-app-discovery.exe
        
  build-macos:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
    
    - name: Install ARM64 target
      run: rustup target add aarch64-apple-darwin
        
    - name: Build — x86_64 MacOS 
      run: cargo build --release --features=cli --target x86_64-apple-darwin --verbose

    - name: Build — ARM64 MacOS
      run: cargo build --release --features=cli --target aarch64-apple-darwin --verbose
      
    - name: Upload x86_64 executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: wolfram-app-discovery--${{ github.event.inputs.ref }}--x86_64-apple-darwin 
        path: target/x86_64-apple-darwin/release/wolfram-app-discovery
      
    - name: Upload ARM64 executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: wolfram-app-discovery--${{ github.event.inputs.ref }}--aarch64-apple-darwin 
        path: target/aarch64-apple-darwin/release/wolfram-app-discovery
